### ISSUE TITLE
Error: No such container: nheqminer

### ISSUE THREAD

**Issue by Jask2002** [unsalted/docker-nheqminer-cuda#1]
# Pre_req
sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
sudo sh -c 'echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/cuda.list'
sudo apt-get update && sudo apt-get install -y --no-install-recommends cuda-drivers

# Unload nouveau
sudo rmmod nouveau

# Install nvidia-docker and nvidia-docker-plugin
wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.1/nvidia-docker_1.0.1-1_amd64.deb
sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb

sudo nvidia-docker run --rm nvidia/cuda nvidia-smi

All Good till this point 

I've pulled 

 sudo nvidia-docker pull unsalted/nheqminer  

Then 

sudo nvidia-docker run --rm -i -d -h nheqminer --name nheqminer unsalted/nheqmine

jas@testGPU:$ sudo nvidia-docker run --rm -i -d -h nheqminer --name nheqminer unsalted/nheqminer
3857553d8aab8203acdd1175f94166f83cc9c48bea2a1f4163fbecbede918c6b

jas@testGPU:$ sudo nvidia-docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

jas@testGPU:$ sudo nvidia-docker exec nheqminer bash -c "nheqminer -l zec-us1.dwarfpool.com:3335 -u t1UoqVgJYfRuZZyaU93FncJzXdhKmx6Vpb5.botbot -cd 0 0"
Error: No such container: nheqminer

What Im missing ?

Thanks,
Jas

**Comment by unsalted** [comment]
It looks like something is failing, try getting rid of `--rm` and checking for errors in the log.

**Comment by unsalted** [comment]
`nvidia-docker run --restart always -i -d -h nheqminer  unsalted/nheqminer \
nheqminer -l zec-us1.dwarfpool.com:3335 -u ZEC_ADDRESS.user -cd 0 ` . This is the main start command.
